apiVersion: v1
kind: Service
metadata:
        name: ftp-service
spec:
        ports:
                - name: ftp
                  port: 22
        type: LoadBalancer
        selector:
                app: ftp
